### PR TITLE
Updated multisync.py and dailysync.py file

### PR DESCRIPTION
**Pull request by gulvaibhav20**
## Fixed the error and added a new file 

- Fixed the error in line 7 and line 8 of multisync.py file and renamed the file to dailysync.py.
- Also added the multisync.py file given in the course.

### CODE REVIEW

**Comment by lakshyajit165** [comment]
@gulvaibhav20 what was the error? I don't remember facing any error while executing this code. Please mention the exact lines along with a detailed error description.

**Comment by gulvaibhav20** [comment]
@lakshyajit165  

**Error -** In values assigned to src and dest variables

**Description -**
While executing the original script ....
The home_add variable contains the value : "/home/username".
Now, while defining the src and dest variables we need to add a "/" before concatenation as originally,
src contained value : "/home/usernamedata/prod" which should actually be 
"/home/username/data/prod". 
This resulted in an error **(Wrong PATH)**.

**Comment by lakshyajit165** [comment]
@gulvaibhav20  thanks for the clarification, but why have you change the portion under the "main" section? I don't think any changes were needed there. We can do one thing, undo the changes under main, and create another PR **for a different branch** for the changes inside it, stating exactly what they do. I

**Comment by gulvaibhav20** [comment]
Ok @lakshyajit165  👍🏻

**Pull request closed without merging**
